export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
export const RESET_QUIZ = 'RESET_QUIZ';
export const LOAD_QUIZZES_SUCCESS = 'LOAD_QUIZZES_SUCCESS';
export const ACTIVE_QUIZ_IS_READY = 'ACTIVE_QUIZ_IS_READY';
export const LOAD_ACTIVE_QUIZ = 'LOAD_ACTIVE_QUIZ';